### ISSUE TITLE
Build fails due to lack of GraalVM

### ISSUE THREAD

**Issue by karianna** [reugn/dev-tools#22]
When executing mvn client:build I get:

`[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.27:compile (default-cli) on project devtools: Error: GraalVM installation directory not found. Either set GRAALVM_HOME as an environment variable or set graalvmHome in client-plugin configuration -> [Help 1]`

easy enough to fix I guess but README may need updating.

**Comment by reugn** [comment]
[v0.6.0](https://github.com/reugn/dev-tools/releases/tag/v0.6.0) has been released with updated installation documentation.
