### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by vikumDheemantha** [reugn/dev-tools#26]
I would like to contribute to the project. But it would be easier if there is a contribution guide. at least which branch do we need to create a PR?

**Comment by reugn** [comment]
Hi @vikumDheemantha, thanks for your interest in the project. For bug fixes, please open a PR to the master branch. If this is a new feature, it would be better to open an issue to discuss.

**Comment by vikumDheemantha** [comment]
Thanks @reugn , I was thinking about adding some features to the project like

- Adding character encoding to the base64 encoder/decoder
- XML formatter
- SQL query formatter
- etc

I will create issue when ever I will ready
